//! Typed-RPC stack (Phase 1, additive).
//!
//! Lives alongside the legacy MCP `Client`/`Transport`/`InProcServer`
//! plumbing. Three orthogonal layers:
//!
//! - [`Adapter`] — byte-stream transport (TCP, async stdio, in-proc).
//! - [`Codec`] — wire format (line-delimited JSON envelope, length-
//!   delimited bincode).
//! - [`Channel`] — pairs an `Adapter` half with a `Codec` for framed
//!   `send`/`recv`.
//!
//! Service traits are generated by the `service!` proc macro
//! (re-exported from `trnsprt`); the macro emits a client struct + a
//! `serve_<service>` async function that loop over a `Channel`.
//!
//! Composing a `Channel` (an in-process client/server pair shown — swap the
//! adapter for `TcpAdapter`/`LocalAdapter` for cross-process):
//! ```ignore
//! use trnsprt::typed::{Channel, InprocAdapter, JsonEnvelopeCodec};
//!
//! let (client_side, server_side) = InprocAdapter::pair();
//! let client = Channel::new(client_side, JsonEnvelopeCodec::new());
//! let server = Channel::new(server_side, JsonEnvelopeCodec::new());
//!
//! // Hand `client` to a generated `FooClient::new(client)`, and run
//! // `serve_foo(server, handler)` on a task; the two exchange framed JSON
//! // values over the chosen codec.
//! ```

pub mod adapter;
pub mod channel;
pub mod codec;
pub mod error;
pub mod local;

pub use adapter::{Adapter, AsyncStdioAdapter, InprocAdapter, TcpAdapter};
pub use channel::Channel;
pub use codec::{BincodeCodec, Codec, JsonEnvelopeCodec};
pub use error::{AdapterError, CodecError, RpcError};
pub use local::{
    bind_kern_listener, connect_kern, BindError, BindOutcome, Endpoint, LocalAdapter,
    LocalListener,
};
#[cfg(unix)]
pub use local::UnixStreamAdapter;
#[cfg(windows)]
pub use local::NamedPipeAdapter;
