//! Server-side implementation of the slice-J `KernRpc` typed surface.
//!
//! Wraps existing kern internals — the same `crate::mcp::Server::tool_*`
//! methods the MCP `tools/call` dispatcher and the legacy
//! `MemoryHandler` already use — so a `kern_rpc` call and an MCP
//! `tools/call` for the same operation produce identical kern-side
//! state transitions.
//!
//! The MCP tool functions return a JSON envelope of the shape
//! `{ "content": [{ "type": "text", "text": "<json string>" }] }` (or
//! `{ "isError": true, ... }` on failure). This handler unwraps that
//! envelope into the strongly-typed wire DTOs declared by
//! [`trnsprt::kern_rpc`].
//!
//! `fork_at` is **not** part of `KernRpc` — see the rationale in
//! `trnsprt::kern_rpc::mod` and the slice-J report.

use std::sync::{Arc, Mutex as StdMutex};

use journal::{EntityTouchedPayload, Entry, Kind, Sink, TouchOp, now_ms};
use serde_json::Value;
use trnsprt::kern_rpc::{
    CallToolReq, CallToolRes, DegradeReq, DegradeRes, DescriptorReq, DescriptorRes, EdgeKind,
    EntityKindLite, EntityRef, EntityStatusLite, ForgetReq, ForgetRes, HealthRes, IngestReq,
    IngestRes, KernRpc, LinkReq, LinkRes, NeighborsReq, NeighborsRes, PulseReq, PulseRes,
    PurposeReq, PurposeRes, QueryReq, QueryRes, SourceLite, TruncateAfterReq, TruncateAfterRes,
};
use trnsprt::typed::{Channel, JsonEnvelopeCodec, LocalListener};
use trnsprt::McpServer;

use crate::base::types::EntityKind;
use crate::memory_service::MemoryService;

/// Build an `EntityTouched` journal entry for slice R agent-driven
/// touches. Factored out so both the production global-sink path and
/// the test capturing-sink path share construction.
fn build_touch_entry(entity_id: &str, op: TouchOp) -> Entry {
    let payload = EntityTouchedPayload {
        entity_id: entity_id.to_string(),
        op,
        fork_id: None,
        ts_ms: now_ms(),
    };
    let v = serde_json::to_value(&payload).unwrap_or(Value::Null);
    Entry::new(Kind::EntityTouched, entity_id, v)
}

/// Emit an `AgentRead` touch for every distinct entity_id in `ids` into
/// the supplied sink. Spam control: the input is deduplicated, so a
/// single query hitting the same entity 50 times produces one event.
pub(crate) fn emit_agent_reads(ids: &[String], sink: &dyn Sink) {
    let mut seen: Vec<&str> = Vec::with_capacity(ids.len());
    for id in ids {
        if id.is_empty() || seen.iter().any(|x| *x == id.as_str()) {
            continue;
        }
        seen.push(id.as_str());
        sink.emit(build_touch_entry(id, TouchOp::AgentRead));
    }
}

/// Emit an `AgentWrite` touch for the supplied entity_id. One event per
/// successful ingest call; no-op when the id is empty (rejected ingest).
pub(crate) fn emit_agent_write(entity_id: &str, sink: &dyn Sink) {
    if entity_id.is_empty() {
        return;
    }
    sink.emit(build_touch_entry(entity_id, TouchOp::AgentWrite));
}

/// Typed-RPC handler bridging `mcp::Server` + `MemoryService` to the
/// `KernRpc` trait generated by `trnsprt::service!`.
#[derive(Clone)]
pub struct KernRpcHandler {
    pub kern: Arc<crate::mcp::Server>,
    pub memory: Arc<StdMutex<MemoryService>>,
}

impl KernRpcHandler {
    pub fn new(kern: Arc<crate::mcp::Server>, memory: Arc<StdMutex<MemoryService>>) -> Self {
        Self { kern, memory }
    }
}

// ---- helpers --------------------------------------------------------------

/// Unwrap the MCP `{ "content": [...] }` envelope to the inner JSON
/// payload the tool emitted. Returns `Err(message)` for `isError`
/// envelopes.
fn unwrap_tool_json(envelope: &Value) -> Result<Value, String> {
    if envelope.get("isError").and_then(|v| v.as_bool()) == Some(true) {
        let msg = envelope
            .pointer("/content/0/text")
            .and_then(|v| v.as_str())
            .unwrap_or("kern tool error")
            .to_string();
        return Err(msg);
    }
    let text = envelope
        .pointer("/content/0/text")
        .and_then(|v| v.as_str())
        .unwrap_or("");
    if text.is_empty() {
        return Ok(Value::Null);
    }
    serde_json::from_str(text).map_err(|e| format!("decode tool result: {e}"))
}

fn entity_kind_from_lite(k: EntityKindLite) -> EntityKind {
    match k {
        EntityKindLite::Fact => EntityKind::Fact,
        EntityKindLite::Claim => EntityKind::Claim,
        EntityKindLite::Document => EntityKind::Document,
        EntityKindLite::Question => EntityKind::Question,
        EntityKindLite::Answer => EntityKind::Answer,
        EntityKindLite::Conclusion => EntityKind::Conclusion,
        // The `Superseded` variant is a status (lifecycle) flag in
        // kern's model, not a kind. Map it to the next-best kind
        // and rely on the caller having set status=Superseded
        // separately if they really meant it.
        EntityKindLite::Superseded => EntityKind::Claim,
    }
}

/// Parse the lower-case kind label echoed by the MCP `tool_query`
/// envelope back into the wire-side [`EntityKindLite`]. Returns `None`
/// for unknown labels so the caller can apply its own default.
fn parse_kind_label(s: &str) -> Option<EntityKindLite> {
    match s {
        "fact" => Some(EntityKindLite::Fact),
        "claim" => Some(EntityKindLite::Claim),
        "document" => Some(EntityKindLite::Document),
        "question" => Some(EntityKindLite::Question),
        "answer" => Some(EntityKindLite::Answer),
        "conclusion" => Some(EntityKindLite::Conclusion),
        _ => None,
    }
}

/// Parse the lower-case status label echoed by the MCP `tool_query`
/// envelope. Anything other than `"superseded"` is treated as Active.
fn parse_status_label(s: &str) -> EntityStatusLite {
    if s == "superseded" {
        EntityStatusLite::Superseded
    } else {
        EntityStatusLite::Active
    }
}

fn entity_kind_to_lite(k: EntityKind) -> EntityKindLite {
    match k {
        EntityKind::Fact => EntityKindLite::Fact,
        EntityKind::Claim => EntityKindLite::Claim,
        EntityKind::Document => EntityKindLite::Document,
        EntityKind::Question => EntityKindLite::Question,
        EntityKind::Answer => EntityKindLite::Answer,
        EntityKind::Conclusion => EntityKindLite::Conclusion,
    }
}

/// Stable tag string for an [`EdgeKind`]. Used as the `reason` argument
/// to `tool_link` and as the wire-side description hint when no
/// explicit text is supplied.
fn edge_kind_tag(k: EdgeKind) -> &'static str {
    match k {
        EdgeKind::Answers => "answers",
        EdgeKind::Supports => "supports",
        EdgeKind::Contradicts => "contradicts",
        EdgeKind::Extends => "extends",
        EdgeKind::Requires => "requires",
        EdgeKind::References => "references",
        EdgeKind::Derives => "derives",
        EdgeKind::Instances => "instances",
        EdgeKind::PartOf => "part_of",
        EdgeKind::Consolidates => "consolidates",
    }
}

// ---- KernRpc impl ---------------------------------------------------------

impl KernRpc for KernRpcHandler {
    fn query(&self, req: QueryReq) -> impl ::core::future::Future<Output = QueryRes> + Send {
        let kern = self.kern.clone();
        async move {
            let mode = if req.mode.is_empty() { "hybrid".to_string() } else { req.mode.clone() };
            let args = serde_json::json!({
                "text": req.text,
                "k": req.k,
                "mode": mode,
                "answer": req.answer,
                "kind": req.kind,
                "scheme": if req.source.is_empty() { Value::Null } else { Value::String(req.source.clone()) },
            });
            let env = kern.tool_query(&args);
            let payload = match unwrap_tool_json(&env) {
                Ok(v) => v,
                Err(_) => return QueryRes::default(),
            };
            let answer = payload
                .get("answer")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let mut hits: Vec<EntityRef> = Vec::new();
            if let Some(arr) = payload.get("entities").and_then(|v| v.as_array()) {
                for e in arr {
                    let id = e.get("id").and_then(|v| v.as_str()).unwrap_or("").to_string();
                    if id.is_empty() {
                        continue;
                    }
                    let score = e.get("score").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
                    let snippet = e
                        .get("text")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .to_string();
                    // Best-effort label = first 80 chars of snippet.
                    let label: String = snippet.chars().take(80).collect();
                    // Slice Z: tool_query envelope echoes kind / scheme
                    // / status directly off the matched Entity, so no
                    // second graph read is needed per hit. Defaults
                    // mirror the legacy fallback when a field is
                    // missing (older envelopes / external clients).
                    let kind = e
                        .get("kind")
                        .and_then(|v| v.as_str())
                        .and_then(parse_kind_label)
                        .unwrap_or(EntityKindLite::Claim);
                    let scheme = e
                        .get("scheme")
                        .and_then(|v| v.as_str())
                        .unwrap_or("inline")
                        .to_string();
                    let status = e
                        .get("status")
                        .and_then(|v| v.as_str())
                        .map(parse_status_label)
                        .unwrap_or(EntityStatusLite::Active);
                    hits.push(EntityRef {
                        id,
                        kind,
                        status,
                        scheme,
                        label,
                        snippet,
                        score,
                    });
                }
            }
            // Slice R: log one `AgentRead` touch per distinct hit so the
            // relay-side Recents ring picks up agent-driven retrievals
            // on journal replay. Dedup is intrinsic to `emit_agent_reads`.
            let ids: Vec<String> = hits.iter().map(|h| h.id.clone()).collect();
            emit_agent_reads(&ids, &journal::GlobalSink);

            QueryRes {
                hits,
                answer,
                fresh: true,
            }
        }
    }

    fn ingest(&self, req: IngestReq) -> impl ::core::future::Future<Output = IngestRes> + Send {
        let kern = self.kern.clone();
        async move {
            let kind = entity_kind_from_lite(req.kind);
            let (source_tag, object_id, section, title, author, url) = match &req.source {
                SourceLite::File { path, section, title, author, url } => (
                    "file",
                    path.clone(),
                    section.clone(),
                    title.clone(),
                    author.clone(),
                    url.clone(),
                ),
                SourceLite::Ticket {
                    system,
                    object_id,
                    section,
                    title,
                    author,
                    url,
                } => (
                    system.as_str(),
                    object_id.clone(),
                    section.clone(),
                    title.clone(),
                    author.clone(),
                    url.clone(),
                ),
                SourceLite::Session { session_id, section, title } => (
                    "session",
                    session_id.clone(),
                    section.clone(),
                    title.clone(),
                    String::new(),
                    String::new(),
                ),
                SourceLite::Agent { agent, object_id, title } => (
                    "agent",
                    object_id.clone(),
                    String::new(),
                    title.clone(),
                    agent.clone(),
                    String::new(),
                ),
                SourceLite::Inline { hash, section } => (
                    "inline",
                    hash.clone(),
                    section.clone(),
                    String::new(),
                    String::new(),
                    String::new(),
                ),
            };
            let descriptor = req.descriptor.clone().unwrap_or_default();
            let args = serde_json::json!({
                "text": req.text,
                "source": source_tag,
                "object_id": object_id,
                "section": section,
                "author": author,
                "title": title,
                "url": url,
                "conf": req.conf,
                "descriptor": descriptor,
                "sync": req.sync,
                "kind": kind as u8,
            });
            let env = kern.tool_ingest(&args);
            let payload = match unwrap_tool_json(&env) {
                Ok(v) => v,
                Err(msg) => {
                    return IngestRes {
                        entity_id: String::new(),
                        status: "rejected".into(),
                        message: msg,
                    };
                }
            };
            let entity_id = payload
                .get("doc_id")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let status = payload
                .get("status")
                .and_then(|v| v.as_str())
                .unwrap_or("queued")
                .to_string();
            let message = payload
                .get("message")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            // Slice R: one `AgentWrite` touch per successful ingest.
            // `emit_agent_write` no-ops when the id is empty (rejected).
            emit_agent_write(&entity_id, &journal::GlobalSink);

            IngestRes {
                entity_id,
                status,
                message,
            }
        }
    }

    fn link(&self, req: LinkReq) -> impl ::core::future::Future<Output = LinkRes> + Send {
        let kern = self.kern.clone();
        async move {
            // The MCP `link` tool stores the supplied free-text on the
            // edge as-is. Prefix with the edge-kind tag when no text
            // was provided so callers retain the kind hint after an
            // LLM auto-fill round-trip.
            let reason_text = if req.text.is_empty() {
                format!("[{}]", edge_kind_tag(req.reason_kind))
            } else {
                req.text.clone()
            };
            let args = serde_json::json!({
                "from": req.from_id,
                "to": req.to_id,
                "reason": reason_text,
            });
            let env = kern.tool_link(&args);
            let payload = match unwrap_tool_json(&env) {
                Ok(v) => v,
                Err(_) => return LinkRes::default(),
            };
            let reason_id = payload
                .get("edge_id")
                .or_else(|| payload.get("id"))
                .or_else(|| payload.get("reason_id"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            LinkRes { reason_id }
        }
    }

    fn neighbors(
        &self,
        req: NeighborsReq,
    ) -> impl ::core::future::Future<Output = NeighborsRes> + Send {
        let kern = self.kern.clone();
        async move {
            // Re-use `tool_query`'s `id`-mode (returns `entity_detail`
            // with edges) to source the depth-1 neighbour set.
            // edge_kinds is treated as a client-side filter on the
            // returned set; depth >1 is not exercised in slice J.
            let _depth = req.depth.min(3);
            let args = serde_json::json!({ "id": req.entity_id });
            let env = kern.tool_query(&args);
            let payload = match unwrap_tool_json(&env) {
                Ok(v) => v,
                Err(_) => return NeighborsRes::default(),
            };
            let mut neighbour_ids: Vec<String> = Vec::new();
            if let Some(edges) = payload.get("edges").and_then(|v| v.as_array()) {
                for e in edges {
                    let from = e.get("from").and_then(|v| v.as_str()).unwrap_or("");
                    let to = e.get("to").and_then(|v| v.as_str()).unwrap_or("");
                    let other = if from == req.entity_id { to } else { from };
                    if other.is_empty() || other == req.entity_id {
                        continue;
                    }
                    if !neighbour_ids.iter().any(|x| x == other) {
                        neighbour_ids.push(other.to_string());
                    }
                    // edge_kinds filter: kern's internal `ReasonKind`
                    // does not yet map 1:1 to the slice-B `EdgeKind`
                    // enum, so we accept all kinds when the caller's
                    // filter is empty and otherwise apply no further
                    // narrowing in slice J. Slice K introduces the
                    // proper mapping.
                }
            }
            let mut neighbors = Vec::with_capacity(neighbour_ids.len());
            for id in neighbour_ids {
                let detail_args = serde_json::json!({ "id": id });
                let env = kern.tool_query(&detail_args);
                let detail = match unwrap_tool_json(&env) {
                    Ok(v) => v,
                    Err(_) => continue,
                };
                let snippet = detail
                    .get("text")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let score = detail.get("score").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
                let kind_u8 = detail.get("kind").and_then(|v| v.as_u64()).unwrap_or(1) as u8;
                let kind_internal = match kind_u8 {
                    0 => EntityKind::Fact,
                    2 => EntityKind::Document,
                    3 => EntityKind::Question,
                    4 => EntityKind::Answer,
                    5 => EntityKind::Conclusion,
                    _ => EntityKind::Claim,
                };
                let (_, scheme, status) = lookup_kind_scheme_status(&kern, &id);
                let label: String = snippet.chars().take(80).collect();
                neighbors.push(EntityRef {
                    id,
                    kind: entity_kind_to_lite(kind_internal),
                    status,
                    scheme,
                    label,
                    snippet,
                    score,
                });
            }
            NeighborsRes { neighbors }
        }
    }

    fn truncate_after(
        &self,
        req: TruncateAfterReq,
    ) -> impl ::core::future::Future<Output = TruncateAfterRes> + Send {
        let memory = self.memory.clone();
        async move {
            let svc = memory.lock().unwrap_or_else(|p| p.into_inner());
            let dropped = svc.truncate_after(req.ts_ms);
            tracing::debug!(target: "kern.kern_rpc", dropped, ts_ms = req.ts_ms, "truncate_after");
            TruncateAfterRes {}
        }
    }

    fn forget(&self, req: ForgetReq) -> impl ::core::future::Future<Output = ForgetRes> + Send {
        let kern = self.kern.clone();
        async move {
            let args = serde_json::json!({ "id": req.id });
            let env = kern.tool_forget(&args);
            // tool_forget emits only `removed_edges` on success; success-implies-removed.
            let removed = unwrap_tool_json(&env).is_ok();
            ForgetRes { removed }
        }
    }

    fn degrade(&self, req: DegradeReq) -> impl ::core::future::Future<Output = DegradeRes> + Send {
        let kern = self.kern.clone();
        async move {
            // Preserve legacy memory_rpc id → query_id remap for tool_degrade.
            let args = serde_json::json!({ "query_id": req.id });
            let env = kern.tool_degrade(&args);
            // tool_degrade emits only `decayed_edges`; success-implies-applied.
            let applied = unwrap_tool_json(&env).is_ok();
            DegradeRes { applied }
        }
    }

    fn health(&self) -> impl ::core::future::Future<Output = HealthRes> + Send {
        let kern = self.kern.clone();
        async move {
            let env = kern.tool_health();
            let payload = match unwrap_tool_json(&env) {
                Ok(v) => v,
                Err(_) => return HealthRes::default(),
            };
            let kerns = payload.get("kerns").and_then(|v| v.as_u64()).unwrap_or(0);
            let entities = payload.get("entities").and_then(|v| v.as_u64()).unwrap_or(0);
            // health_stats has no data_dir field; default to empty.
            let data_dir = payload
                .get("data_dir")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            HealthRes {
                ok: true,
                data_dir,
                kerns,
                entities,
            }
        }
    }

    fn purpose(&self, req: PurposeReq) -> impl ::core::future::Future<Output = PurposeRes> + Send {
        let kern = self.kern.clone();
        async move {
            let args = serde_json::json!({ "text": req.text });
            let _ = kern.tool_purpose(&args);
            PurposeRes::default()
        }
    }

    fn descriptor(
        &self,
        req: DescriptorReq,
    ) -> impl ::core::future::Future<Output = DescriptorRes> + Send {
        let kern = self.kern.clone();
        async move {
            let args = serde_json::json!({
                "action": req.action,
                "name": req.name,
                "description": req.description,
            });
            let _ = kern.tool_descriptor(&args);
            DescriptorRes::default()
        }
    }

    fn pulse(&self, req: PulseReq) -> impl ::core::future::Future<Output = PulseRes> + Send {
        let kern = self.kern.clone();
        async move {
            let args = serde_json::json!({ "strength": req.strength });
            let _ = kern.tool_pulse(&args);
            PulseRes::default()
        }
    }

    fn call_tool(
        &self,
        req: CallToolReq,
    ) -> impl ::core::future::Future<Output = CallToolRes> + Send {
        let kern = self.kern.clone();
        async move {
            // Forward to the existing MCP `call_tool` dispatcher so the
            // proxy in `kern mcp` can relay any stdio MCP `tools/call`
            // request over kern.sock without enumerating every tool.
            let envelope = match McpServer::call_tool(&*kern, &req.name, &req.args) {
                Ok(tr) => serde_json::json!({
                    "content": tr.content,
                    "isError": tr.is_error,
                }),
                Err(e) => serde_json::json!({
                    "content": [{
                        "type": "text",
                        "text": format!("kern_rpc::call_tool: {e}"),
                    }],
                    "isError": true,
                }),
            };
            CallToolRes { envelope }
        }
    }
}

/// Look up an entity's kind / source-scheme / status via the kern
/// graph. Returns kern-side defaults when the entity is missing so
/// `query` results still surface (a missing entity row is possible
/// during ingest race conditions).
fn lookup_kind_scheme_status(
    server: &Arc<crate::mcp::Server>,
    id: &str,
) -> (EntityKindLite, String, EntityStatusLite) {
    use crate::base::search::find_entity;
    let g = match server.graph.read() {
        Ok(g) => g,
        Err(_) => {
            return (
                EntityKindLite::Claim,
                "inline".into(),
                EntityStatusLite::Active,
            );
        }
    };
    match find_entity(&g, id) {
        Some((ent, _)) => (
            entity_kind_to_lite(ent.kind),
            ent.source.scheme().to_string(),
            if ent.is_superseded() {
                EntityStatusLite::Superseded
            } else {
                EntityStatusLite::Active
            },
        ),
        None => (
            EntityKindLite::Claim,
            "inline".into(),
            EntityStatusLite::Active,
        ),
    }
}

// ---- listener -------------------------------------------------------------

/// Accept loop over a pre-bound [`LocalListener`]. Caller (run_server)
/// owns the singleton-aware bind so it can react to `BindOutcome::
/// AlreadyRunning` by exiting 0 before any other daemon scaffolding
/// spins up.
///
/// Per accept: spawn a task that wraps the local-socket adapter in a
/// JSON-envelope `Channel` and runs the generated `serve_kern_rpc`
/// service loop. Errors on a single connection are logged; they do not
/// take the listener down.
pub async fn serve_kern_rpc_loop(mut listener: LocalListener, handler: KernRpcHandler) {
    loop {
        let adapter = match listener.accept().await {
            Ok(a) => a,
            Err(e) => {
                tracing::warn!(target: "kern.kern_rpc", error = %e, "accept");
                continue;
            }
        };
        let handler = handler.clone();
        tokio::spawn(async move {
            let channel = Channel::new(adapter, JsonEnvelopeCodec::new());
            if let Err(e) = trnsprt::kern_rpc::serve_kern_rpc(channel, handler).await {
                tracing::warn!(target: "kern.kern_rpc", error = %e, "serve loop");
            }
        });
    }
}

#[cfg(test)]
mod recents_touch_tests {
    //! Slice R: cover the agent-side touch hooks placed inside
    //! `KernRpc::query` / `KernRpc::ingest`. Tests drive the
    //! `emit_agent_reads` / `emit_agent_write` helpers directly with a
    //! `CapturingSink` so they don't depend on the process-global
    //! `DayJournal` or on standing up an `mcp::Server` graph.
    use super::*;
    use std::sync::Mutex;

    #[derive(Default)]
    struct CapturingSink {
        entries: Mutex<Vec<Entry>>,
    }
    impl Sink for CapturingSink {
        fn emit(&self, entry: Entry) {
            self.entries.lock().unwrap().push(entry);
        }
    }

    fn parse_touches(sink: &CapturingSink) -> Vec<(String, TouchOp)> {
        sink.entries
            .lock()
            .unwrap()
            .iter()
            .filter_map(journal::EntityTouchedEvent::from_entry)
            .map(|e| (e.entity_id, e.op))
            .collect()
    }

    #[test]
    fn query_emits_one_agent_read_per_distinct_hit() {
        let sink = CapturingSink::default();
        let ids = vec!["a".to_string(), "b".to_string(), "c".to_string()];
        emit_agent_reads(&ids, &sink);
        let touches = parse_touches(&sink);
        assert_eq!(touches.len(), 3);
        assert!(touches.iter().all(|(_, op)| *op == TouchOp::AgentRead));
        let got_ids: Vec<&str> = touches.iter().map(|(i, _)| i.as_str()).collect();
        assert_eq!(got_ids, vec!["a", "b", "c"]);
    }

    #[test]
    fn query_dedups_repeated_ids_to_one_event() {
        let sink = CapturingSink::default();
        // Spam control: a query that returns 5 hits for the same entity
        // must produce exactly one AgentRead, not five.
        let ids = vec!["x".to_string(); 5];
        emit_agent_reads(&ids, &sink);
        let touches = parse_touches(&sink);
        assert_eq!(touches.len(), 1);
        assert_eq!(touches[0], ("x".to_string(), TouchOp::AgentRead));
    }

    #[test]
    fn query_skips_empty_ids() {
        let sink = CapturingSink::default();
        emit_agent_reads(&["".to_string(), "y".to_string(), "".to_string()], &sink);
        let touches = parse_touches(&sink);
        assert_eq!(touches.len(), 1);
        assert_eq!(touches[0].0, "y");
    }

    #[test]
    fn ingest_emits_one_agent_write_per_call() {
        let sink = CapturingSink::default();
        emit_agent_write("ent-1", &sink);
        let touches = parse_touches(&sink);
        assert_eq!(touches.len(), 1);
        assert_eq!(touches[0], ("ent-1".to_string(), TouchOp::AgentWrite));
    }

    #[test]
    fn ingest_skips_emit_when_id_empty() {
        // Rejected ingest paths return entity_id="" — should not emit.
        let sink = CapturingSink::default();
        emit_agent_write("", &sink);
        assert!(sink.entries.lock().unwrap().is_empty());
    }
}

#[cfg(test)]
mod envelope_parse_tests {
    //! Slice Z: tool_query envelope echoes kind/scheme/status directly
    //! off the matched Entity, eliminating the per-hit graph re-read in
    //! `KernRpc::query`. These tests cover the lower-case label parsers
    //! the query path uses to lift envelope strings into the typed
    //! [`EntityKindLite`] / [`EntityStatusLite`] DTOs.
    use super::*;

    #[test]
    fn parse_kind_label_round_trips_every_kind() {
        for k in [
            EntityKind::Fact,
            EntityKind::Claim,
            EntityKind::Document,
            EntityKind::Question,
            EntityKind::Answer,
            EntityKind::Conclusion,
        ] {
            let label = k.as_str();
            let lite = parse_kind_label(label).expect("known label parses");
            assert_eq!(lite, entity_kind_to_lite(k), "round-trip for {label}");
        }
    }

    #[test]
    fn parse_kind_label_unknown_returns_none() {
        assert!(parse_kind_label("").is_none());
        assert!(parse_kind_label("bogus").is_none());
        // Superseded is a status, never a kind label.
        assert!(parse_kind_label("superseded").is_none());
    }

    #[test]
    fn parse_status_label_recognises_superseded() {
        assert_eq!(parse_status_label("superseded"), EntityStatusLite::Superseded);
    }

    #[test]
    fn parse_status_label_defaults_to_active() {
        assert_eq!(parse_status_label("active"), EntityStatusLite::Active);
        assert_eq!(parse_status_label(""), EntityStatusLite::Active);
        assert_eq!(parse_status_label("garbage"), EntityStatusLite::Active);
    }
}
