name = "relay"

cursor = "#07fda0"

background = "#0f1414"
surface = "#0f1414"

foreground = "#dfdfdf"
selection = "#3e6356"
muted = "#38443f"
emphasis = "#00ff88"

primary_bright = "#00ff88"
primary = "#00cc88"
primary_dim = "#055033"

alert_bright = "#d35454"
alert = "#d35454"
alert_dim = "#d35454"

warning = "#f3d448"
info = "#26deff"
