//! `MemoryService` (HashMap-backed) + `MemoryHandler` (typed-RPC adapter).
//!
//! `MemoryService` is the in-memory store used by Adjust mode's
//! `truncate_after` flow. It's intentionally a HashMap shim — the
//! truncate-by-timestamp semantics don't need the full graph.
//!
//! `MemoryHandler` implements `protocol::memory::MemoryRpc`. The
//! `truncate_after` method routes to `MemoryService`. The other 9
//! methods route to the same kern internals that the MCP `tools/call`
//! dispatcher uses (`crate::mcp::Server::tool_*`), so a typed-RPC call
//! and an MCP `tools/call` for the same operation produce identical
//! JSON.

use std::collections::HashMap;
use std::sync::Mutex;

#[derive(Debug, Clone)]
pub struct MemoryEntry {
	pub ts_ms: u64,
	pub key: String,
	pub text: String,
}

#[derive(Default)]
pub struct MemoryService {
	entries: Mutex<HashMap<String, MemoryEntry>>,
}

impl MemoryService {
	pub fn new() -> Self {
		Self::default()
	}

	pub fn insert(&self, e: MemoryEntry) {
		let mut g = self.entries.lock().unwrap_or_else(|p| p.into_inner());
		g.insert(e.key.clone(), e);
	}

	/// Drop entries with `ts_ms > input`. Returns the number removed so
	/// callers can surface a trace line for visibility.
	pub fn truncate_after(&self, ts_ms: u64) -> usize {
		let mut g = self.entries.lock().unwrap_or_else(|p| p.into_inner());
		let before = g.len();
		g.retain(|_, e| e.ts_ms <= ts_ms);
		before - g.len()
	}

	pub fn len(&self) -> usize {
		self.entries.lock().unwrap_or_else(|p| p.into_inner()).len()
	}

	pub fn is_empty(&self) -> bool {
		self.len() == 0
	}
}

// -- Typed-RPC handler bridging `MemoryService` + `crate::mcp::Server` to the
// `MemoryRpc` trait generated by `trnsprt::service!`. The MCP tool
// dispatcher (`crate::mcp::Server::handle_tool_call`) is the source of
// truth for what each operation does and what JSON shape it returns;
// each method below assembles the same `serde_json::Value` of arguments
// the MCP path passes and forwards to the matching `tool_*`.

use std::sync::{Arc, Mutex as StdMutex};

use protocol::memory::{
	DegradeReq, DescriptorReq, ForgetReq, IngestReq, LinkReq, MemoryResp, PulseReq, PurposeReq,
	QueryReq,
};

#[derive(Clone)]
pub struct MemoryHandler {
	pub inner: Arc<StdMutex<MemoryService>>,
	pub kern: Arc<crate::mcp::Server>,
}

impl MemoryHandler {
	pub fn new(inner: Arc<StdMutex<MemoryService>>, kern: Arc<crate::mcp::Server>) -> Self {
		Self { inner, kern }
	}
}

impl protocol::memory::MemoryRpc for MemoryHandler {
	fn ingest(&self, req: IngestReq) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		let kern = self.kern.clone();
		async move {
			let args = serde_json::json!({
				"text": req.text,
				"source": req.source,
				"object_id": req.object_id,
				"section": req.section,
				"author": req.author,
				"title": req.title,
				"url": req.url,
				"conf": req.conf,
				"descriptor": req.descriptor,
				"sync": req.sync,
			});
			kern.tool_ingest(&args)
		}
	}
	fn query(&self, req: QueryReq) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		let kern = self.kern.clone();
		async move {
			let args = serde_json::json!({
				"text": req.text,
				"id": req.id,
				"k": req.k,
				"mode": req.mode,
				"answer": req.answer,
				"sort": req.sort,
				"ascending": req.ascending,
				"source": req.source,
				"kind": req.kind,
				"since": req.since,
				"before": req.before,
				"min_conf": req.min_conf,
				"valid_at": req.valid_at,
			});
			kern.tool_query(&args)
		}
	}
	fn link(&self, req: LinkReq) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		let kern = self.kern.clone();
		async move {
			let args = serde_json::json!({
				"from": req.from,
				"to": req.to,
				"reason": req.reason,
			});
			kern.tool_link(&args)
		}
	}
	fn forget(&self, req: ForgetReq) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		let kern = self.kern.clone();
		async move {
			let args = serde_json::json!({ "id": req.id });
			kern.tool_forget(&args)
		}
	}
	fn degrade(&self, req: DegradeReq) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		// `DegradeReq { id, strength }` <-> MCP `tool_degrade { query_id }`.
		// `strength` has no kern counterpart on the MCP side (decay is
		// computed from constants); pass `id` through as `query_id`.
		let kern = self.kern.clone();
		async move {
			let args = serde_json::json!({ "query_id": req.id });
			kern.tool_degrade(&args)
		}
	}
	fn health(&self) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		let kern = self.kern.clone();
		async move { kern.tool_health() }
	}
	fn purpose(&self, req: PurposeReq) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		let kern = self.kern.clone();
		async move {
			let args = serde_json::json!({ "text": req.text });
			kern.tool_purpose(&args)
		}
	}
	fn descriptor(
		&self,
		req: DescriptorReq,
	) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		let kern = self.kern.clone();
		async move {
			let args = serde_json::json!({
				"action": req.action,
				"name": req.name,
				"description": req.description,
			});
			kern.tool_descriptor(&args)
		}
	}
	fn pulse(&self, req: PulseReq) -> impl ::core::future::Future<Output = MemoryResp> + Send {
		// `PulseReq { query_id }` is a Phase-1 holdover — the kern MCP
		// `pulse` tool takes only a `strength` (default 1.0) and always
		// pulses the root. Ignore `query_id` and forward with default
		// strength so a typed-RPC `pulse` produces the same effect as
		// the MCP one.
		let kern = self.kern.clone();
		async move {
			let _ = req;
			let args = serde_json::json!({});
			kern.tool_pulse(&args)
		}
	}
	fn truncate_after(
		&self,
		ts_ms: u64,
	) -> impl ::core::future::Future<Output = Result<(), String>> + Send {
		let inner = self.inner.clone();
		async move {
			let svc = inner.lock().unwrap_or_else(|p| p.into_inner());
			let dropped = svc.truncate_after(ts_ms);
			tracing::debug!(target: "kern.memory_rpc", dropped, ts_ms, "truncate_after");
			Ok(())
		}
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn truncate_drops_newer_only() {
		let s = MemoryService::new();
		s.insert(MemoryEntry { ts_ms: 10, key: "a".into(), text: "x".into() });
		s.insert(MemoryEntry { ts_ms: 20, key: "b".into(), text: "y".into() });
		s.insert(MemoryEntry { ts_ms: 30, key: "c".into(), text: "z".into() });
		assert_eq!(s.truncate_after(20), 1);
		assert_eq!(s.len(), 2);
	}
}
