//! `trnsprt` — kern's transport + typed-RPC layer.
//!
//! Two stacks live here, layered bottom-up:
//!
//! ```text
//!   services      search::SearchSvc        kern_rpc::KernRpc      (generated by service!)
//!   ───────────────────────────────────────────────────────────
//!   typed-RPC     typed::Channel<C> + Codec (JsonEnvelope|Bincode)   framed send/recv
//!                 typed::Adapter (Inproc | stdio | TCP)
//!   ───────────────────────────────────────────────────────────
//!   MCP (legacy)  McpServer / Client / Registry / Transport      JSON-RPC, wire in `mod server`
//! ```
//!
//! **MCP transport** — the original boundary: `McpServer`, `Transport`,
//! `Client`, `Registry`, `InProcTransport` plus their value types. The JSON-RPC
//! wire format is an implementation detail hidden inside `mod server`.
//!
//! **Typed-RPC** ([`typed`]) — an additive, codec-framed [`typed::Channel`] over
//! a `Transport` adapter. The [`service!`] macro generates a trait + client +
//! serve loop per service from one declaration; [`search`] and [`kern_rpc`] are
//! the two services, sharing DTOs where their wire shapes overlap.

mod client;
mod error;
mod http;
mod inproc;
mod registry;
mod server;
mod transport;
mod types;

pub use client::Client;
pub use error::McpError;
pub use inproc::InProcTransport;
pub use registry::{LiveServer, Registry};
pub use http::serve_http;
pub use server::{serve_rw, serve_stdio, McpServer};
pub use transport::{ChildStdio, Transport};
pub use types::{ServerId, ToolResult, ToolSchema};

pub const PROTOCOL_VERSION: &str = "2024-11-05";

// The `service!` macro emits `::trnsprt::*` paths; when the macro is
// invoked inside this crate (see `mod search`), self-aliasing makes
// those paths resolve.
extern crate self as trnsprt;

// -- Typed-RPC stack (Phase 1, additive). MCP plumbing above is untouched.
pub mod typed;
pub use trnsprt_macros::service;

// -- SearchSvc — typed-RPC search surface. Re-exports the generated
//    trait/client/serve fn through `search::*`.
pub mod search;

// -- KernRpc — typed-RPC surface exposing kern's read+write ops to
//    sub-agents and other clients. Sibling to `search::SearchSvc`;
//    DTOs are intentionally shared where the wire shape overlaps.
pub mod kern_rpc;

/// Internals re-exported **solely** for the code the [`service!`] macro
/// generates — it emits fully-qualified `::trnsprt::__private::*` paths so the
/// expansion needs no `use` in the caller crate.
///
/// STABILITY: this is NOT part of the public API. Anything here may be added,
/// removed, or have its version bumped in any release — never depend on or
/// import from `__private` directly; use the generated service client/trait.
#[doc(hidden)]
pub mod __private {
	pub use bytes;
	pub use futures;
	pub use serde_json;
	pub use tokio;
	pub use tokio_util;
}
